x_min: -200.0
x_max: 200.0
y_min: -200.0
y_max: 200.0

Car_Length_0: 0.1
Car_Length: 8.0665
Car_Width: 2.73

# A*
a_star_resolution_meters: 0.5
Road_Side_Point_interval: 0.5   # Interval distance for extracting road boundary obstacle points

Publish_Road_Side_Point: true
Publish_Lidar_Point: true
Publish_Filter_Lidar_Point: true
Publish_A_Star_Map: true
Publish_A_star_Path: true

# Trajectory_Optimization
init_time: 1.0
A_Star_Point_interval: 1        # Take 1 point every n points in A* to fit the path
traj_opimiz_weight_time: 1                
traj_opimiz_weight_energy_x: 1
traj_opimiz_weight_energy_y: 1
traj_opimiz_weight_energy_w: 1
traj_opimiz_weight_position_x: 1                
traj_opimiz_weight_position_y: 1                
traj_opimiz_weight_position_w: 1                

# SDF_Optimization
# Find t_star
coarse_grid_size: 0.1                 # Coarse grid size
find_t_star_time_step: 0.1           # Time step
eta: 0.01                             # Learning rate
c: 0.1                                # Armijo control parameter
tol: 1e-6                             # Tolerance
max_iter: 1000                        # Maximum iterations

# Compute SDF
SDF_TEST: false 
SDF_resolution: 0.8                   # Resolution for SDF computation
SDF_safety_hor: 1                     # Safety distance from obstacles

# Optimization
SDF_opimiz_times_max: 10000          # Max optimization steps
SDF_opimiz_weight_time: 1              
SDF_opimiz_weight_energy_x: 1
SDF_opimiz_weight_energy_y: 1
SDF_opimiz_weight_energy_w: 1
SDF_opimiz_weight_swept_volume: 0.1
SDF_opimiz_weight_safety:  1
