x_min: -200.0
x_max: 200.0
y_min: -200.0
y_max: 200.0

Car_Length_0: 0.1
Car_Length: 8.0665
Car_Width: 2.73

# A*
a_star_resolution_meters: 0.5
Road_Side_Point_interval: 0.5   #提取道路边界障碍点的间隔距离

Publish_Road_Side_Point: true
Publish_Lidar_Point: true
Publish_Filter_Lidar_Point: true
Publish_A_Star_Map: true
Publish_A_star_Path: true


# Trajectory_Opimization
init_time: 1.0
A_Star_Point_interval: 1        #在A*中每隔n个点取1个点拟合路径
traj_opimiz_weight_time: 1                
traj_opimiz_weight_energy_x: 1
traj_opimiz_weight_energy_y: 1
traj_opimiz_weight_energy_w: 1
traj_opimiz_weight_position_x: 1                
traj_opimiz_weight_position_y: 1                
traj_opimiz_weight_position_w: 1                

# SDF_Opimization
#找t_star
coarse_grid_size: 0.1                 #大网格尺寸
find_t_star_time_step: 0.1            #时间步长
eta: 0.01                             #学习率
c: 0.1                                #Armijo控制参数
tol: 1e-6                             #容差
max_iter: 1000                        #最大步数

#计算SDF
SDF_TEST: false 
SDF_resolution: 0.8                    #SDF计算分辨率
SDF_safety_hor: 1                      #距离障碍物安全距离
#优化
SDF_opimiz_times_max: 10000           #最大优化步数
SDF_opimiz_weight_time: 1              
SDF_opimiz_weight_energy_x: 1
SDF_opimiz_weight_energy_y: 1
SDF_opimiz_weight_energy_w: 1
SDF_opimiz_weight_swept_volume: 0.1
SDF_opimiz_weight_safety:  1